@TaskFlow_Api_HostAddress = http://localhost:5289

GET {{TaskFlow_Api_HostAddress}}/api/health
Accept: application/json

###

GET {{TaskFlow_Api_HostAddress}}/openapi/v1.json
Accept: application/json

###